### ISSUE TITLE
Software does not work on example data

### ISSUE THREAD

**Issue by MTutino** [segrelabgenomics/QTLEnrich#5]
Hi,

I am trying to use the tool on the GTEx and GWAS example data, before using it on mine, but it does not seem to work. 
Data used:
UKBB Height as from example, lifted over to hg38 as from example
GTEx V8 Whole_Blood
Null and confounders tables as provided
GENCODE V26

Log: 
preparing gwas
Preparing confounders and null table...
This may take a few minutes

/lustre/groups/itg/teams/zeggini/projects/child_diabesity/tools/QTLEnrich/src/qtl_gwas_parsing.py:160: FutureWarning: Columnar iteration over characters
will be deprecated in future releases.
  df["chr"],df["pos"],df["Allele"] = df["variant"].str.split("_",2).str
parsing qtls

Whole_Blood
computing tss distance. Checking for gencode file.
merging
computing observed fold-enrichment
Preparing data for permutations... This may take a few minutes.

Tissue_Whole_Blood
Running with 1000 permutations for 0 QTLs with an observed fold enrichment of 0...                                                                      
Traceback (most recent call last):
  File "/lustre/groups/itg/teams/zeggini/projects/child_diabesity/tools/QTLEnrich/src/QTLEnrichV2.py", line 112, in <module>                            
    enrichment_p_value_dict,adjusted_fold_enrichment_dict,upper_bound_confidence_interval_dict,lower_bound_confidence_interval_dict,pi_1_dict,true_trait_
dict = rand_null_samp_permute_matching_confounders.sample_match_null_confounders(log_file,month_date,output_files_directory,args.qtl_type,gwas_trait,conf
ounders_table,null_table,significant_qtl_gwas_dict,observed_fold,args.gwas_p_value,null_option=args.null_option,num_permutations=args.lower_bound_permuta
tions,upper_bound_permutations=args.upper_bound_permutations,lambda_factor=args.lambda_factor,independent_ranking=args.independent_ranking,compute_tss_di
stance=args.compute_tss_distance,keep_null_variants=args.keep_null_variants,keep_pvalue_matrix=args.keep_pvalue_matrix,interaction_qtl_dict=interaction_q
tl_dict,num_quantiles=args.num_quantiles)
  File "/lustre/groups/itg/teams/zeggini/projects/child_diabesity/tools/QTLEnrich/src/rand_null_samp_permute_matching_confounders.py", line 468, in sampl
e_match_null_confounders
    return_matrix, fold_enrichments= permute_null_variants(log_file,date,output_files_directory,qtl_type,tissue,trait,observed_fold_enrichment=observed_f
old_enrichment,
  File "/lustre/groups/itg/teams/zeggini/projects/child_diabesity/tools/QTLEnrich/src/rand_null_samp_permute_matching_confounders.py", line 270, in permu
te_null_variants
    temp_names_df, temp_p_values_df, low_p_value_indices = map(np.array, zip(*[random_sampling_for_variant(variant, options_tables, variant_to_bins, num_
permutations, use_num, p_value_cutoff) for variant in variant_list]))
ValueError: not enough values to unpack (expected 3, got 0)

I would really appreciate your input on this.

Thank you

**Comment by Ketomihine** [comment]
Hello, I am also very interested in this algorithm, but the Null and confounders tables provided by the authors can no longer be downloaded. Could you please share them with me? Thank you. @MTutino

**Comment by splicingrats** [comment]
@MTutino Hi, I have the same problem, "0 QTLs with an observed fold enrichment of 0". Have you solved it?
